version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: fundsmith
      POSTGRES_USER: fundsmith
      POSTGRES_PASSWORD: fundsmith
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fundsmith"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: ./backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/fundsmith
      SPRING_DATASOURCE_USERNAME: fundsmith
      SPRING_DATASOURCE_PASSWORD: fundsmith
      DEMO_ENABLED: "true"
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8080
    depends_on:
      - backend

volumes:
  postgres_data: